package:
  name: yacht
  version: 1.0

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir -vvv"
  script_env:
    - PYTHON

requirements:
  build:
    - python
    - setuptools
  host:
    - python >3.6
    - pip
  run:
    - python >3.6
    - gcc
    - sourmash >=4.8.3,<5
    - rust
    - scipy
    - numpy
    - pandas
    - scikit-learn
    - codecov
    - pytest
    - pytest-cov
    - loguru
    - maturin >=1,<2
    - tqdm
    - pip
    - biom-format
    - pytaxonkit
    - sourmash_plugin_branchwater
    - openpyxl

about:
  home: https://github.com/KoslickiLab/YACHT
  license: MIT License
  summary: YACHT is a mathematically rigorous hypothesis test for the presence or absence of organisms in a metagenomic sample, based on average nucleotide identity (ANI).
