import os
import sys
import numpy as np
import warnings
from scipy.stats import binom
from scipy.special import betaincinv
import pandas as pd
import zipfile
from tqdm import tqdm
from multiprocessing import Pool
import sourmash
import glob
from typing import List, Set, Tuple, Dict
from .utils import load_signature_with_ksize, decompress_all_sig_files, MIN_ANI_THRESHOLD
# Configure Loguru logger
from loguru import logger
from .cov_calc import cov_calc

"""
Hypothesis Recovery and Coverage Analysis Module

This module implements YACHT's core statistical framework for organism detection
in metagenomic samples, with integrated coverage modeling and abundance estimation.
"""

warnings.filterwarnings("ignore")

logger.remove()
logger.add(
    sys.stdout, format="{time:YYYY-MM-DD HH:mm:ss} - {level} - {message}", level="INFO"
)

SIG_SUFFIX = ".sig"


def get_organisms_with_nonzero_overlap(
    manifest: pd.DataFrame,
    sample_file: str,
    scale: int,
    ksize: int,
    num_threads: int,
    path_to_genome_temp_dir: str,
    path_to_sample_temp_dir: str,
) -> List[str]:
    """
    This function runs the sourmash multisearch to find the organisms that have non-zero overlap with the sample.
    :param manifest: a dataframe with the following columns:
                        'organism_name',
                        'md5sum',
                        'num_unique_kmers_in_genome_sketch',
                        'num_total_kmers_in_genome_sketch',
                        'genome_scale_factor',
                        'num_exclusive_kmers_in_sample_sketch',
                        'num_total_kmers_in_sample_sketch',
                        'sample_scale_factor',
                        'min_coverage'
    :param sample_file: string (path to the sample signature file)
    :param scale: int (scale factor)
    :param ksize: string (size of kmer)
    :param num_threads: int (number of threads to use for parallelization)
    :param path_to_genome_temp_dir: string (path to the genome temporary directory generated by the training step)
    :param path_to_sample_temp_dir: string (path to the sample temporary directory)
    :return: a list of organism names that have non-zero overlap with the sample
    """
    # run the sourmash multisearch
    # prepare the input files for the sourmash multisearch
    # unzip the sourmash signature file to the temporary directory
    logger.info("Unzipping the sample signature zip file")
    with zipfile.ZipFile(sample_file, "r") as sample_zip_file:
        sample_zip_file.extractall(path_to_sample_temp_dir)
    all_gz_files = glob.glob(f"{path_to_sample_temp_dir}/signatures/*.sig.gz")
    # decompress all signature files
    logger.info(f"Decompressing {len(all_gz_files)} .sig.gz files using {num_threads} threads.")
    decompress_all_sig_files(all_gz_files, num_threads)

    sample_sig_file = pd.DataFrame(
        [
            os.path.join(path_to_sample_temp_dir, "signatures", sig_file)
            for sig_file in os.listdir(
                os.path.join(path_to_sample_temp_dir, "signatures")
            )
        ]
    )
    sample_sig_file_path = os.path.join(path_to_sample_temp_dir, "sample_sig_file.txt")
    sample_sig_file.to_csv(sample_sig_file_path, header=False, index=False)

    organism_sig_file = pd.DataFrame(
        [
            os.path.join(path_to_genome_temp_dir, "signatures", md5sum + SIG_SUFFIX)
            for md5sum in manifest["md5sum"]
        ]
    )
    organism_sig_file_path = os.path.join(
        path_to_sample_temp_dir, "organism_sig_file.txt"
    )
    organism_sig_file.to_csv(organism_sig_file_path, header=False, index=False)

    # run the sourmash multisearch
    cmd = f"sourmash scripts multisearch {sample_sig_file_path} {organism_sig_file_path} -s {scale} -k {ksize} -c {num_threads} -t 0 -o {os.path.join(path_to_sample_temp_dir, 'sample_multisearch_result.csv')}"
    logger.info(f"Running sourmash multisearch with command: {cmd}")
    exit_code = os.system(cmd)
    if exit_code != 0:
        raise ValueError(f"Error running sourmash multisearch with command: {cmd}")

    # read the multisearch result, only if the file is not empty
    multisearch_result_file = os.path.join(path_to_sample_temp_dir, "sample_multisearch_result.csv")
    try:
        multisearch_result = pd.read_csv(
            multisearch_result_file,
            sep=",",
            header=0,
        )
    except pd.errors.EmptyDataError:
        print('ERROR: Multisearch file is empty. Likely there are no microorganisms in your sample, or something went wrong', flush=True)
        exit(0)

    multisearch_result = multisearch_result.drop_duplicates().reset_index(drop=True)

    return multisearch_result["match_name"].to_list()


# Global variable for sharing sample signature across worker processes
_worker_sample_sig = None

def _init_coverage_worker(sample_sig):
    """
    Initializer for worker processes to set up shared sample signature.

    :param sample_sig: Sample signature to be shared across all workers
    """
    global _worker_sample_sig
    _worker_sample_sig = sample_sig

def _calculate_coverage_worker(args):
    """
    Worker function for parallel coverage calculation.
    Uses global _worker_sample_sig instead of passing it as argument to avoid pickling overhead.

    :param args: Tuple of (md5sum, path_to_genome_temp_dir, ksize)
    :return: Result from cov_calc or None if error occurs
    """
    md5sum, path_to_genome_temp_dir, ksize = args
    try:
        sig = load_signature_with_ksize(
            os.path.join(path_to_genome_temp_dir, "signatures", md5sum + SIG_SUFFIX),
            ksize,
        )
        return cov_calc(_worker_sample_sig, sig)
    except Exception as e:
        logger.warning(f"Error calculating coverage for {md5sum}: {e}")
        return None


def get_exclusive_hashes(
    manifest: pd.DataFrame,
    nontrivial_organism_names: List[str],
    sample_sig: sourmash.SourmashSignature,
    ksize: int,
    path_to_genome_temp_dir: str,
    num_threads: int = 16,
    winner_takes_all: bool = False,
    batch_size: int = 1000,
) -> Tuple[List[Tuple[int, int]], pd.DataFrame, pd.DataFrame]:
    """
    This function gets the unique hashes exclusive to each of the organisms that have non-zero overlap with the sample, and
    then find how many are in the sample.
    :param manifest: a dataframe with the following columns:
                        'organism_name',
                        'md5sum',
                        'num_unique_kmers_in_genome_sketch',
                        'num_total_kmers_in_genome_sketch',
                        'genome_scale_factor',
                        'num_exclusive_kmers_in_sample_sketch',
                        'num_total_kmers_in_sample_sketch',
                        'sample_scale_factor',
                        'min_coverage'
    :param nontrivial_organism_names: a list of organism names that have non-zero overlap with the sample
    :param sample_sig: the sample signature
    :param ksize: int (size of kmer)
    :param path_to_genome_temp_dir: string (path to the genome temporary directory generated by the training step)
    :param num_threads: int (number of threads to use for parallel coverage calculation, default: 16)
    :param winner_takes_all: bool (enable winner-takes-all k-mer reassignment and relative abundance, default: False)
    :param batch_size: int (batch size for winner-takes-all processing, default: 1000)
    :return:
        a list of tuples, each tuple contains the following information:
            1. the number of unique hashes exclusive to the organism under consideration
            2. the number of unique hashes exclusive to the organism under consideration that are in the sample
        a new manifest dataframe that only contains the organisms that have non-zero overlap with the sample
        a dataframe with coverage statistics for each organism
    """
    def __find_exclusive_hashes(
        md5sum: str,
        path_to_temp_dir: str,
        ksize: int,
        single_occurrence_hashes: Set[int],
    ) -> Set[int]:
        # load genome signature
        sig = load_signature_with_ksize(
            os.path.join(path_to_temp_dir, "signatures", md5sum + SIG_SUFFIX), ksize
        )
        return {hash for hash in sig.minhash.hashes if hash in single_occurrence_hashes}
    
    # get manifest information for the organisms that have non-zero overlap with the sample
    sub_manifest = manifest.loc[
        manifest["organism_name"].isin(nontrivial_organism_names), :
    ].reset_index(drop=True)
    organism_md5sum_list = sub_manifest["md5sum"].to_list()

    single_occurrence_hashes: Set[int] = set()  # Corrected type annotation
    multiple_occurrence_hashes: Set[int] = set()
    for md5sum in tqdm(organism_md5sum_list, desc="Processing organism signatures"):
        sig = load_signature_with_ksize(
            os.path.join(path_to_genome_temp_dir, "signatures", md5sum + SIG_SUFFIX),
            ksize,
        )
        for hash in sig.minhash.hashes:
            if hash in multiple_occurrence_hashes:
                continue
            elif hash in single_occurrence_hashes:
                single_occurrence_hashes.remove(hash)
                multiple_occurrence_hashes.add(hash)
            else:
                single_occurrence_hashes.add(hash)


    del multiple_occurrence_hashes  # free up memory

    # Find hashes that are unique to each organism
    logger.info("Finding hashes that are unique to each organism")
    exclusive_hashes_org = []
    for md5sum in tqdm(organism_md5sum_list, desc="Finding exclusive hashes"):
        exclusive_hashes_org.append(
            __find_exclusive_hashes(
                md5sum, path_to_genome_temp_dir, ksize, single_occurrence_hashes
            )
        )

    del single_occurrence_hashes  # free up memory

    # Get sample hashes
    sample_hashes = set(sample_sig.minhash.hashes)

    # Calculate coverage statistics for each organism (parallelized)
    logger.info(f"Calculating coverage statistics using {num_threads} threads")

    # Calculate (organism) chunk size for progress visibility
    chunk_size = max(1, len(organism_md5sum_list) // (num_threads * 50))
    logger.info(f"Using chunk size of {chunk_size} for parallel processing")

    with Pool(processes=num_threads, initializer=_init_coverage_worker, initargs=(sample_sig,)) as pool:
        # Prepare arguments for parallel processing (sample_sig shared via initializer to avoid pickling overhead)
        args_list = [
            (md5sum, path_to_genome_temp_dir, ksize)
            for md5sum in organism_md5sum_list
        ]
        # Use imap_unordered for better performance (order doesn't matter for coverage stats)
        stats_list = list(
            tqdm(
                pool.imap_unordered(_calculate_coverage_worker, args_list, chunksize=chunk_size),
                total=len(organism_md5sum_list),
                desc="Processing coverage per organism"
            )
        )

    # Filter out None results (from errors)
    stats_list = [stats for stats in stats_list if stats is not None]

    if not stats_list:
        raise ValueError("No coverage statistics were successfully calculated")

    final_stats_df = pd.concat(stats_list, ignore_index=True)

    # Add organism_name to final_stats_df for merging (stats are in same order as sub_manifest)
    final_stats_df['organism_name'] = sub_manifest['organism_name'].values

    del stats_list # free up memory

    # Find hashes that are unique to each organism and in the sample
    logger.info("Finding hashes that are unique to each organism and in the sample")
    exclusive_hashes_info = []
    for i, exclusive_hashes in enumerate(
        tqdm(exclusive_hashes_org, desc="Matching exclusive hashes with sample")
    ):
        exclusive_hashes_info.append(
            (len(exclusive_hashes), len(exclusive_hashes.intersection(sample_hashes)))
        )

    # Conditionally run winner-takes-all (memory-intensive but provides relative abundance)
    if winner_takes_all:
        logger.info("Building winner map for k-mer reassignment (winner-takes-all strategy)")
        winner_map = build_winner_map(final_stats_df, path_to_genome_temp_dir, ksize, batch_size)
        final_stats_df = estimate_relative_abundance(final_stats_df, winner_map, sample_sig, batch_size)

        # Free up memory by dropping genome_sketch column (no longer needed)
        if 'genome_sketch' in final_stats_df.columns:
            logger.info("Releasing genome signature objects to free memory")
            final_stats_df.drop(columns=['genome_sketch'], inplace=True)
    else:
        logger.info("Skipping winner-takes-all (not enabled). Use --winner_takes_all to enable relative abundance estimation.")
        # Add placeholder columns for consistency
        final_stats_df['rel_abund'] = float('nan')
        final_stats_df['kmers_lost'] = 0

        # Also drop genome_sketch to save memory
        if 'genome_sketch' in final_stats_df.columns:
            final_stats_df.drop(columns=['genome_sketch'], inplace=True)

    return exclusive_hashes_info, sub_manifest, final_stats_df


def build_winner_map(
    final_stats_df: pd.DataFrame,
    path_to_genome_temp_dir: str,
    ksize: int,
    batch_size: int = 1000
) -> Dict[int, Tuple[float, str]]:
    """
    Creates a "winner map" procedure that assigns k-mers to the organism with the highest ANI.
    Uses memory-efficient batch processing.

    This implements the "winner takes all" strategy from sylph (Shaw and Yu, 2024) where
    shared k-mers are assigned to the organism with the best ANI match, preventing double-counting.
    Please note that this differs from the approach in sylph in that the procedure is run once, rather than
    twice.

    :param final_stats_df: DataFrame with coverage statistics including organism_name,
                          final_est_ani, and genome_sketch columns
    :param path_to_genome_temp_dir: Path to the directory containing genome signature files
    :param ksize: k-mer size
    :param batch_size: Number of organisms to process per batch (default: 1000)
    :return: Dictionary mapping k-mer hash -> (ani, organism_name)
             Only the organism with highest ANI "wins" each k-mer
    """
    winner_map = {}
    total_organisms = len(final_stats_df)

    logger.info(f"Building winner map for {total_organisms} organisms (batch size: {batch_size})")

    # Process in batches to control memory usage
    for batch_start in range(0, total_organisms, batch_size):
        batch_end = min(batch_start + batch_size, total_organisms)
        batch_num = batch_start // batch_size + 1
        total_batches = (total_organisms + batch_size - 1) // batch_size

        for idx in tqdm(
            range(batch_start, batch_end),
            desc=f"Building winner map (batch {batch_num}/{total_batches})",
            total=batch_end - batch_start
        ):
            row = final_stats_df.iloc[idx]
            organism_name = row['organism_name']
            ani = row['final_est_ani']

            # Skip organisms with no ANI estimate
            if pd.isna(ani):
                continue

            genome_sig = row['genome_sketch']

            # For each k-mer, check if it should be reassigned
            for kmer in genome_sig.minhash.hashes.keys():
                if kmer not in winner_map or ani > winner_map[kmer][0]:
                    winner_map[kmer] = (ani, organism_name)

    logger.info(f"Winner map built with {len(winner_map)} k-mers assigned")

    return winner_map


def estimate_relative_abundance(
    final_stats_df: pd.DataFrame,
    winner_map: Dict[int, Tuple[float, str]],
    sample_sig: sourmash.SourmashSignature,
    batch_size: int = 1000
) -> pd.DataFrame:
    """
    Estimates the relative abundance of each organism based on winner_map k-mer assignments.
    Uses memory-efficient batch processing.

    After winner_map assigns shared k-mers to organisms with highest ANI, this calculates:
    1. How many k-mers each organism "lost" to others (kmers_lost)
    2. Total coverage from k-mers "won" by each organism (used for relative abundance)
    3. Relative abundance normalized across all organisms

    :param final_stats_df: DataFrame with coverage statistics
    :param winner_map: k-mer to (ANI, organism_name) mapping from build_winner_map()
    :param sample_sig: Sample signature with k-mer abundances
    :param batch_size: Number of organisms to process per batch (default: 1000)
    :return: Updated DataFrame with rel_abund and kmers_lost columns populated
    """
    logger.info("Estimating relative abundance using winner map (memory-efficient mode)")

    # Initialize columns
    final_stats_df['kmers_lost'] = 0
    final_stats_df['rel_abund'] = 0.0

    sample_hashes = sample_sig.minhash.hashes
    total_organisms = len(final_stats_df)

    # Process in batches to reduce memory usage
    for batch_start in range(0, total_organisms, batch_size):
        batch_end = min(batch_start + batch_size, total_organisms)
        batch_num = batch_start // batch_size + 1
        total_batches = (total_organisms + batch_size - 1) // batch_size

        for idx in tqdm(
            range(batch_start, batch_end),
            desc=f"Calculating relative abundance (batch {batch_num}/{total_batches})",
            total=batch_end - batch_start
        ):
            row = final_stats_df.iloc[idx]
            organism_name = row['organism_name']
            genome_sig = row['genome_sketch']

            kmers_lost_count = 0
            total_coverage = 0.0

            # Check each k-mer in this genome
            for kmer in genome_sig.minhash.hashes.keys():
                # Check if this organism "won" this k-mer
                if kmer in winner_map:
                    winner_organism = winner_map[kmer][1]

                    if winner_organism != organism_name:
                        # This k-mer was reassigned to another organism
                        kmers_lost_count += 1
                    else:
                        # This organism won this k-mer - count its coverage
                        if kmer in sample_hashes:
                            total_coverage += sample_hashes[kmer]

            final_stats_df.at[idx, 'kmers_lost'] = kmers_lost_count
            final_stats_df.at[idx, 'rel_abund'] = total_coverage

    # Normalize relative abundance to sum to 1.0 across all organisms
    total_abundance = final_stats_df['rel_abund'].sum()
    if total_abundance > 0:
        final_stats_df['rel_abund'] = final_stats_df['rel_abund'] / total_abundance
        logger.info(f"Relative abundance normalized (total coverage: {total_abundance:.2f})")
    else:
        logger.warning("No coverage found for relative abundance calculation")

    return final_stats_df


def get_alt_mut_rate(
    nu: int, thresh: int, ksize: int, significance: float = 0.99
) -> float:
    """
    Computes the alternative mutation rate for a given significance level. I.e. how much higher would the mutation rate
    have needed to be in order to have a false positive rate of significance (since we are setting the false negative
    rate to significance by design)?
    :param nu: int (Number of k-mers exclusive to the organism under consideration)
    :param thresh: Number of exclusive k-mers I would need to observe in order to reject the null hypothesis (i.e.
    accept that the organism is present)
    :param ksize: int (k-mer size)
    :param significance: value between 0 and 1 expressing the desired false positive rate (and by design, the false
    negative rate)
    :return: float (alternative mutation rate; how much higher would the mutation rate have needed to be in order to
    make FP and FN rates equal to significance)
    """
    # Replace binary search with the regularized incomplete Gamma function inverse: Solve[significance ==
    #   BetaRegularized[1 - (1 - mutCurr)^k, nu - thresh,
    #    1 + thresh], mutCurr]
    # per mathematica
    mut = 1 - (1 - betaincinv(nu - thresh, 1 + thresh, significance)) ** (1 / ksize)
    return -1.0 if np.isnan(mut) else mut


def single_hyp_test(
    exclusive_hashes_info_org: Tuple[int, int],
    ksize: int,
    significance: float = 0.99,
    ani_thresh: float = 0.95,
    min_coverage: int = 1,
) -> Tuple[bool, float, int, int, int, int, float, float]:
    """
    Performs a single hypothesis test for the presence of a genome in a metagenome.
    :param exclusive_hashes_info_org: a tuple containing the following information:
            1. the number of unique hashes exclusive to this genome under consideration
            2. the number of unique hashes exclusive to this genome under consideration that are in the sample
    :param ksize: int (k-mer size)
    :param significance: float (significance level for the hypothesis test)
    :param ani_thresh: threshold for ANI (i.e. how similar do the genomes need to be in order to be considered the same)
    :param min_coverage: minimum coverage of the genome under consideration in the metagenome (float in [0, 1])
    :return: A whole bunch of stuff
    """
    # get the number of unique k-mers
    num_exclusive_kmers = exclusive_hashes_info_org[0]
    # mutation rate
    non_mut_p = (ani_thresh) ** ksize
    # # assuming coverage of 1, how many unique k-mers would I need to observe in order to reject the null hypothesis?
    # acceptance_threshold_wo_coverage = binom.ppf(1-significance, num_exclusive_kmers, non_mut_p)
    # # what is the actual confidence of the test?
    # actual_confidence_wo_coverage = 1-binom.cdf(acceptance_threshold_wo_coverage, num_exclusive_kmers, non_mut_p)
    # number of unique k-mers I would see given a coverage of min_coverage
    num_exclusive_kmers_coverage = int(num_exclusive_kmers * min_coverage)
    # how many unique k-mers would I need to observe in order to reject the null hypothesis,
    # assuming coverage of min_cov?
    acceptance_threshold_with_coverage = binom.ppf(
        1 - significance, num_exclusive_kmers_coverage, non_mut_p
    )
    # what is the actual confidence of the test, assuming coverage of min_cov?
    actual_confidence_with_coverage = 1 - binom.cdf(
        acceptance_threshold_with_coverage, num_exclusive_kmers_coverage, non_mut_p
    )
    # # what is the alternative mutation rate? I.e. how much higher would the mutation rate (resp. how low of ANI)
    # # have needed to be in order to have a false positive rate of significance
    # # (since we are setting the false negative rate to significance by design)?
    # alt_confidence_mut_rate = get_alt_mut_rate(num_exclusive_kmers, acceptance_threshold_wo_coverage, ksize,
    #                                            significance=significance)
    # same as above, but assuming coverage of min_cov
    alt_confidence_mut_rate_with_coverage = get_alt_mut_rate(
        num_exclusive_kmers_coverage,
        acceptance_threshold_with_coverage,
        ksize,
        significance=significance,
    )

    # How many unique k-mers do I actually see?
    num_matches = exclusive_hashes_info_org[1]
    # calculate the p-value considering the coverage
    if num_matches <= num_exclusive_kmers_coverage:
        p_val = binom.cdf(num_matches, num_exclusive_kmers_coverage, non_mut_p)
    else:
        p_val = 1.0
    # is the genome present? Takes coverage into account
    in_sample_est = (num_matches >= acceptance_threshold_with_coverage) and (
        num_matches != 0
    )
    # return in_sample_est, p_val, num_exclusive_kmers, num_exclusive_kmers_coverage, num_matches, \
    #        acceptance_threshold_wo_coverage, acceptance_threshold_with_coverage, actual_confidence_wo_coverage, \
    #        actual_confidence_with_coverage, alt_confidence_mut_rate, alt_confidence_mut_rate_with_coverage
    return (
        in_sample_est,
        p_val,
        num_exclusive_kmers,
        num_exclusive_kmers_coverage,
        num_matches,
        acceptance_threshold_with_coverage,
        actual_confidence_with_coverage,
        alt_confidence_mut_rate_with_coverage,
    )


def hypothesis_recovery(
    manifest: pd.DataFrame,
    sample_info_set: Tuple[str, sourmash.SourmashSignature],
    path_to_genome_temp_dir: str,
    min_coverage_list: List[float],
    scale: int,
    ksize: int,
    significance: float = 0.99,
    ani_thresh: float = 0.95,
    num_threads: int = 16,
    winner_takes_all: bool = False,
    batch_size: int = 1000,
):
    """
    Go through each of the organisms that have non-zero overlap with the sample and perform a hypothesis test for the
    presence of that organism in the sample: have we seen enough k-mers exclusive to that organism to conclude that
    an organism with ANI > ani_thresh (to the one under consideration) is present in the sample?
    :param manifest: a dataframe with the following columns:
                        'organism_name',
                        'md5sum',
                        'num_unique_kmers_in_genome_sketch',
                        'num_total_kmers_in_genome_sketch',
                        'genome_scale_factor',
                        'num_exclusive_kmers_in_sample_sketch',
                        'num_total_kmers_in_sample_sketch',
                        'sample_scale_factor',
                        'min_coverage'
    :param sample_info_set: a set of information about the sample, including the sample signature location and the sample signature object
    :param path_to_genome_temp_dir: path to the genome temporary directory generated by the training step
    :param min_coverage_list: a list of minimum coverage values
    :param scale: scale factor
    :param ksize: k-mer size
    :param significance: significance level for the hypothesis test
    :param ani_thresh: threshold for ANI (i.e. how similar do the genomes need to be in order to be considered the same)
    :param num_threads: number of threads to use for parallelization
    :return: a list of pandas dataframe with the results of the hypothesis tests based on different min_coverage values
    """

    # unpack the sample info set
    sample_file, sample_sig = sample_info_set

    # create a temporary directory for the sample
    sample_dir = os.path.dirname(sample_file)
    sample_name = os.path.basename(sample_file).replace(".sig.zip", "")
    path_to_sample_temp_dir = os.path.join(
        sample_dir, f"sample_{sample_name}_intermediate_files"
    )
    if os.path.exists(path_to_sample_temp_dir):
        # if exists, remove it
        logger.info(f"Removing existing temporary directory: {path_to_sample_temp_dir}")
        os.system(f"rm -rf {path_to_sample_temp_dir}")
    os.makedirs(path_to_sample_temp_dir)

    # Find the organisms that have non-zero overlap with the sample
    nontrivial_organism_names = get_organisms_with_nonzero_overlap(
        manifest,
        sample_file,
        scale,
        ksize,
        num_threads,
        path_to_genome_temp_dir,
        path_to_sample_temp_dir,
    )

    # Get the unique hashes exclusive to each of the organisms that have non-zero overlap with the sample
    exclusive_hashes_info, manifest, final_stats_df = get_exclusive_hashes(
        manifest, nontrivial_organism_names, sample_sig, ksize, path_to_genome_temp_dir,
        num_threads, winner_takes_all, batch_size
    )

    # Set up the results dataframe columns
    # n.b. that the output of cov_calc is not being incorporated here; instead it's being returned separately, as a pandas dataframe.
    given_columns = [
        "in_sample_est",  # Main output: Boolean indicating whether genome is present in sample
        "p_vals",  # Probability of observing this or more extreme result at ANI threshold.
        "num_exclusive_kmers_to_genome",  # Number of k-mers exclusive to genome
        "num_exclusive_kmers_to_genome_coverage",  # Number of k-mers exclusive to genome, assuming coverage of min_cov
        "num_matches",  # Number of k-mers exclusive to genome that are present in the sample
        # 'acceptance_threshold_wo_coverage',  # Acceptance threshold without adjusting for coverage
        # (how many k-mers need to be present in order to reject the null hypothesis)
        "acceptance_threshold_with_coverage",  # Acceptance threshold with adjusting for coverage
        # 'actual_confidence_wo_coverage',  # Actual confidence without adjusting for coverage
        "actual_confidence_with_coverage",  # Actual confidence with adjusting for coverage
        # 'alt_confidence_mut_rate',  # Mutation rate such that at this mutation rate, false positive rate = p_val.
        # Does not account for min_coverage parameter.
        "alt_confidence_mut_rate_with_coverage",  # same as above, but accounting for min_coverage parameter
    ]

    # Using multiprocessing.Pool to parallelize the execution
    manifest_list = []
    for min_coverage in tqdm(min_coverage_list, desc="Computing hypothesis recovery"):
        logger.info(f"Computing hypothesis recovery for min_coverage={min_coverage}")
        with Pool(processes=num_threads) as p:
            params = (
                (
                    exclusive_hashes_info[i],
                    ksize,
                    significance,
                    ani_thresh,
                    min_coverage,
                )
                for i in range(len(exclusive_hashes_info))
            )
            results = p.starmap(single_hyp_test, params)
        logger.info(f"Finished computing all results for min_coverage value: {min_coverage}")

        # Create a pandas dataframe to store the results
        results = pd.DataFrame(results, columns=given_columns)

        # combine the results with the manifest
        manifest["min_coverage"] = min_coverage
        manifest_list.append(pd.concat([manifest, results], axis=1))

    # Merge coverage statistics into each manifest DataFrame
    # Select key coverage columns to include in output (including winner_map results)
    coverage_cols = [
        'organism_name',
        'naive_ani',
        'final_est_ani',
        'final_est_cov',
        'mean_cov',
        'median_cov',
        'lambda_status',
        'ani_ci',
        'lambda_ci',
        'rel_abund',      # Relative abundance from winner_map
        'kmers_lost'      # K-mers reassigned to other organisms
    ]
    coverage_stats = final_stats_df[coverage_cols].copy()

    # Merge coverage stats into each manifest in the list
    for i in range(len(manifest_list)):
        manifest_list[i] = manifest_list[i].merge(
            coverage_stats,
            on='organism_name',
            how='left'  # Keep all organisms, even those without coverage stats
        )

    # ============================================================================
    # ANI Threshold Filtering
    # ============================================================================
    #
    # After winner_map k-mer reassignment, filter organisms with low ANI.
    #
    # Why filter?
    #   - Removes poor matches (distant relatives, contamination, low complexity)
    #   - Improves result quality by eliminating noise
    #   - Standard practice in metagenomic profiling
    #
    # Threshold: MIN_ANI_THRESHOLD = 0.90 (90% ANI)
    #   - Matches sylph's MIN_ANI_DEF default
    #   - 90% ANI commonly used for genus-level distinction
    #   - Well-supported by microbial genomics literature
    #
    # Implementation:
    #   Keep organisms with final_est_ani >= 0.90 OR NaN ANI
    #   (NaN kept because hypothesis test may still be valid via exclusive k-mers)
    #
    # Customization:
    #   To change threshold, modify MIN_ANI_THRESHOLD in utils.py
    #
    logger.info(f"Filtering organisms with final_est_ani < {MIN_ANI_THRESHOLD} ({MIN_ANI_THRESHOLD*100:.0f}% ANI)")
    for i in range(len(manifest_list)):
        initial_count = len(manifest_list[i])
        # Keep organisms with ANI >= threshold OR organisms with no ANI estimate (NaN)
        manifest_list[i] = manifest_list[i][
            (manifest_list[i]['final_est_ani'] >= MIN_ANI_THRESHOLD) |
            (manifest_list[i]['final_est_ani'].isna())
        ].reset_index(drop=True)
        filtered_count = initial_count - len(manifest_list[i])
        if filtered_count > 0:
            logger.info(f"  Filtered {filtered_count} organisms below ANI threshold from min_coverage={manifest_list[i]['min_coverage'].iloc[0] if len(manifest_list[i]) > 0 else 'N/A'} results")

    return manifest_list
