{% set version = "1.3.0" %}

package:
  name: yacht
  version: {{ version }}

source:
  url: https://github.com/KoslickiLab/YACHT/releases/download/v{{ version  }}/yacht-{{ version  }}.tar.gz
  sha256: 93adb23ad4f143d48c9f0ea661fe2283ff42e9c51e073a05460596ecabc65214

build:
  number: 1
  script: bash build.sh  # Use the build.sh script to handle compilation

requirements:
  build:
    - {{ compiler('cxx') }}       # Adds platform-specific C++ compiler (g++, clang, MSVC)
    - make                        # Ensures that Make is available (for Unix)
    - python >3.6                 # Python version
    - pip
    - setuptools 

  host:
    - python >3.6
    - pip
    - pandas
    - pytaxonkit
    - scipy
    - sourmash
    - loguru
    - tqdm
    - biom-format
    - numpy
    - setuptools
    - requests

  run:
    - python >3.6
    - sourmash >=4.8.3,<5
    - rust
    - scipy
    - requests
    - numpy
    - pandas
    - scikit-learn
    - codecov
    - pytest
    - pytest-cov
    - loguru
    - maturin >=1,<2
    - tqdm
    - biom-format
    - pytaxonkit
    - openpyxl
    - ruff


test:
  commands:
    - yacht --help

about:
  home: https://github.com/KoslickiLab/YACHT
  summary: 'YACHT is a mathematically rigorous hypothesis test for the presence or absence of organisms in a metagenomic sample, based on average nucleotide identity (ANI).'
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/KoslickiLab/YACHT
  doc_url: https://github.com/KoslickiLab/YACHT/wiki

extra:
  skip-lints:
    - should_use_compilers
  identifiers:
    - doi:10.1093/bioinformatics/btae047
  recipe-maintainers:
    - chunyuma
    - dkoslicki